<?php
$paginator = $this->paginator;
$columns = array(
    'id' => 'Id',
    'ownerId' => 'Owner',
    'created' => 'Created',
);
?>
<table>
    <thead>
        <tr>
        <?php foreach($columns as $columnId => $columnLabel):?>
            <td><?php echo $columnLabel?></td>
        <?php endforeach;?>
        </tr>
    </thead>
    <tbody>
        <?php foreach($paginator as $item):?>
            <tr>
                <td><a href="<?php echo $this->url('KapitchiIdentity/Identity/Update', array('id' => $item['id']))?>">Edit</a></td>
                <?php foreach($columns as $columnId => $columnLabel):?>
                <td><?php echo $item[$columnId]?></td>
                <?php endforeach?>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php echo $this->paginationControl($paginator,
                            'Sliding',
                            'paginator'); ?>
